#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Python 示例脚本生成器（交互式 + 参数模式）

目标：
- 尽量让用户灵活选择要生成的示例（支持多选）
- 提供默认 model id，用户可自行修改
- API Key 可交互输入，并可选择写入项目根目录的 .env（更安全、可控）

生成的示例脚本默认写入：python/generated/*.py
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Tuple


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = PROJECT_ROOT / "python" / "generated"
DEFAULT_MODEL_ID = "doubao-seed-2-0-lite-260215"
DEFAULT_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3"


@dataclass(frozen=True)
class ExampleKind:
    key: str
    label: str
    description: str
    filename: str
    renderer: Callable[[str, str], str]  # model_id, base_url


def _render_common_prelude(model_id: str, base_url: str) -> str:
    # Keep generated scripts self-contained and safe: no API key hardcoding.
    return f'''# -*- coding: utf-8 -*-
"""
This file is generated by python/gen_example.py

Notes:
- API Key: read from environment variable ARK_API_KEY
- Model ID: edit MODEL_ID below if needed
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from volcenginesdkarkruntime import Ark


MODEL_ID = "{model_id}"
BASE_URL = "{base_url}"


def _load_dotenv_if_present() -> None:
    """
    Best-effort .env loader for local runs.
    It only reads ARK_API_KEY and does NOT export globally.
    """
    # Generated scripts live at python/generated/*.py, so project root is parents[2].
    project_root = Path(__file__).resolve().parents[2]
    env_path = project_root / ".env"
    if not env_path.exists():
        return

    try:
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k == "ARK_API_KEY" and v and not os.environ.get("ARK_API_KEY"):
                os.environ["ARK_API_KEY"] = v
                return
    except Exception:
        # Ignore dotenv errors; fall back to direct env var.
        return


def _get_api_key() -> str:
    _load_dotenv_if_present()
    api_key = os.environ.get("ARK_API_KEY")
    if api_key:
        return api_key.strip()

    # Non-interactive mode should fail fast.
    if sys.stdin is None or not sys.stdin.isatty():
        raise RuntimeError("ARK_API_KEY 未设置，且当前为非交互模式。请先 export ARK_API_KEY 或写入项目根目录 .env。")

    api_key = input("请输入 ARK_API_KEY (回车确认): ").strip()
    if not api_key:
        raise RuntimeError("ARK_API_KEY 不能为空。")
    os.environ["ARK_API_KEY"] = api_key
    return api_key


def _new_client(api_key: str) -> Ark:
    # Keep base_url explicit to avoid confusion in different regions/environments.
    return Ark(api_key=api_key, base_url=BASE_URL)
'''


def _render_chat_basic(model_id: str, base_url: str) -> str:
    return (
        _render_common_prelude(model_id, base_url)
        + '''

def main() -> None:
    api_key = _get_api_key()
    client = _new_client(api_key)

    prompt = "请用简洁的语言解释什么是人工智能。"
    completion = client.chat.completions.create(
        model=MODEL_ID,
        messages=[
            {"role": "system", "content": "你是一个专业的开发助手。"},
            {"role": "user", "content": prompt},
        ],
    )

    print(completion.choices[0].message.content)


if __name__ == "__main__":
    main()
'''
    )


def _render_chat_streaming(model_id: str, base_url: str) -> str:
    return (
        _render_common_prelude(model_id, base_url)
        + '''

def main() -> None:
    api_key = _get_api_key()
    client = _new_client(api_key)

    prompt = "常见的十字花科植物有哪些？"
    completion = client.chat.completions.create(
        model=MODEL_ID,
        messages=[
            {"role": "user", "content": prompt},
        ],
        stream=True,
    )

    for chunk in completion:
        delta = chunk.choices[0].delta
        if delta and getattr(delta, "content", None):
            print(delta.content, end="")
    print()


if __name__ == "__main__":
    main()
'''
    )


def _render_multi_turn_chat(model_id: str, base_url: str) -> str:
    return (
        _render_common_prelude(model_id, base_url)
        + '''

def main() -> None:
    api_key = _get_api_key()
    client = _new_client(api_key)

    messages = [
        {"role": "system", "content": "你是一个专业的开发助手。"},
        {"role": "user", "content": "用一句话介绍北京。"},
        {"role": "assistant", "content": "北京是中国的首都，拥有深厚的历史文化底蕴与现代都市活力。"},
        {"role": "user", "content": "再用一句话介绍上海。"},
    ]

    completion = client.chat.completions.create(
        model=MODEL_ID,
        messages=messages,
    )

    print(completion.choices[0].message.content)


if __name__ == "__main__":
    main()
'''
    )


def _render_image_understanding(model_id: str, base_url: str) -> str:
    return (
        _render_common_prelude(model_id, base_url)
        + '''

def main() -> None:
    api_key = _get_api_key()
    client = _new_client(api_key)

    image_url = "https://ark-project.tos-cn-beijing.volces.com/doc_image/ark_demo_img_1.png"
    response = client.responses.create(
        model=MODEL_ID,
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_image", "image_url": image_url},
                    {"type": "input_text", "text": "请描述这张图片的主要内容。"},
                ],
            }
        ],
    )

    print(response)


if __name__ == "__main__":
    main()
'''
    )


def _render_tools_web_search(model_id: str, base_url: str) -> str:
    return (
        _render_common_prelude(model_id, base_url)
        + '''

def main() -> None:
    api_key = _get_api_key()
    client = _new_client(api_key)

    response = client.responses.create(
        model=MODEL_ID,
        input=[{"role": "user", "content": "今天上海天气如何？"}],
        tools=[
            {
                "type": "web_search",
                "max_keyword": 2,
            }
        ],
    )

    print(response)


if __name__ == "__main__":
    main()
'''
    )


def _render_deep_thinking(model_id: str, base_url: str) -> str:
    return (
        _render_common_prelude(model_id, base_url)
        + '''

def main() -> None:
    api_key = _get_api_key()
    # Deep thinking may take longer; use a larger timeout.
    client = Ark(api_key=api_key, base_url=BASE_URL, timeout=1800)

    prompt = "我要研究深度思考模型与非深度思考模型区别的课题，怎么体现我的专业性？"
    completion = client.chat.completions.create(
        model=MODEL_ID,
        messages=[{"role": "user", "content": prompt}],
    )

    # When deep thinking is triggered, some models may provide reasoning_content.
    message = completion.choices[0].message
    reasoning = getattr(message, "reasoning_content", None)
    if reasoning:
        print(reasoning)
    print(message.content)


if __name__ == "__main__":
    main()
'''
    )


KINDS: Dict[str, ExampleKind] = {
    "chat_basic": ExampleKind(
        key="chat_basic",
        label="基础对话",
        description="chat.completions.create（最简单可运行）",
        filename="chat_basic_demo.py",
        renderer=_render_chat_basic,
    ),
    "chat_streaming": ExampleKind(
        key="chat_streaming",
        label="流式输出",
        description="chat.completions.create(stream=True)",
        filename="chat_streaming_demo.py",
        renderer=_render_chat_streaming,
    ),
    "multi_turn_chat": ExampleKind(
        key="multi_turn_chat",
        label="多轮对话",
        description="使用 messages 列表构造多轮上下文",
        filename="multi_turn_chat_demo.py",
        renderer=_render_multi_turn_chat,
    ),
    "image_understanding": ExampleKind(
        key="image_understanding",
        label="图片理解",
        description="responses.create 输入图片 + 文本",
        filename="image_understanding_demo.py",
        renderer=_render_image_understanding,
    ),
    "tools_web_search": ExampleKind(
        key="tools_web_search",
        label="联网工具",
        description="responses.create + web_search tool",
        filename="tools_web_search_demo.py",
        renderer=_render_tools_web_search,
    ),
    "deep_thinking": ExampleKind(
        key="deep_thinking",
        label="深度思考",
        description="长 timeout + reasoning_content（如模型支持）",
        filename="deep_thinking_demo.py",
        renderer=_render_deep_thinking,
    ),
}


def _split_kinds_arg(value: str) -> List[str]:
    items = []
    for part in value.split(","):
        k = part.strip()
        if k:
            items.append(k)
    return items


def _prompt_yes_no(question: str, default_yes: bool = True) -> bool:
    suffix = "Y/n" if default_yes else "y/N"
    while True:
        ans = input(f"{question} ({suffix}): ").strip().lower()
        if not ans:
            return default_yes
        if ans in {"y", "yes"}:
            return True
        if ans in {"n", "no"}:
            return False
        print("请输入 y 或 n。")


def _update_dotenv(path: Path, key: str, value: str) -> None:
    lines: List[str] = []
    if path.exists():
        lines = path.read_text(encoding="utf-8").splitlines()

    out: List[str] = []
    replaced = False
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=")
    for line in lines:
        if pattern.match(line) and not replaced:
            out.append(f"{key}={value}")
            replaced = True
        else:
            out.append(line)

    if not replaced:
        if out and out[-1].strip() != "":
            out.append("")
        out.append(f"{key}={value}")

    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def _choose_kinds_interactively() -> List[str]:
    keys = list(KINDS.keys())
    print("")
    print("请选择要生成的 Python 示例（可多选）：")
    for i, k in enumerate(keys, start=1):
        kind = KINDS[k]
        print(f"{i}. {kind.label} ({kind.key}) - {kind.description}")

    print("")
    print("输入示例：1,3,5  或  all")
    raw = input("请选择（默认 1）: ").strip().lower()
    if not raw:
        return [keys[0]]
    if raw == "all":
        return keys

    selected: List[str] = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        if part.isdigit():
            idx = int(part)
            if 1 <= idx <= len(keys):
                selected.append(keys[idx - 1])
            else:
                raise ValueError(f"无效序号: {part}")
        else:
            if part in KINDS:
                selected.append(part)
            else:
                raise ValueError(f"无效类型: {part}")

    # Deduplicate while preserving order.
    dedup: List[str] = []
    seen = set()
    for k in selected:
        if k not in seen:
            dedup.append(k)
            seen.add(k)
    return dedup


def generate(out_dir: Path, kinds: Iterable[str], model_id: str, base_url: str) -> List[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for key in kinds:
        if key not in KINDS:
            raise ValueError(f"unknown kind: {key}")
        kind = KINDS[key]
        content = kind.renderer(model_id, base_url)
        path = out_dir / kind.filename
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate Ark Python example scripts.")
    parser.add_argument("--kinds", help="Comma-separated kinds (e.g. chat_basic,tools_web_search)")
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR), help="Output directory for generated scripts")
    parser.add_argument("--model-id", default=DEFAULT_MODEL_ID, help="Default model id to embed in generated scripts")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help="Ark base_url for generated scripts")
    args = parser.parse_args(argv)

    out_dir = Path(args.out_dir).expanduser()
    model_id = (args.model_id or DEFAULT_MODEL_ID).strip()
    base_url = (args.base_url or DEFAULT_BASE_URL).strip()

    if args.kinds:
        kinds = _split_kinds_arg(args.kinds)
        written = generate(out_dir=out_dir, kinds=kinds, model_id=model_id, base_url=base_url)
        for p in written:
            print(str(p))
        return 0

    # Interactive mode
    print("==================================================")
    print("   Ark Python 示例脚本生成器")
    print("==================================================")
    print("")

    api_key = os.environ.get("ARK_API_KEY", "").strip()
    if not api_key:
        api_key = input("请输入 ARK_API_KEY（回车确认）: ").strip()
        if not api_key:
            print("ARK_API_KEY 不能为空。", file=sys.stderr)
            return 2
        os.environ["ARK_API_KEY"] = api_key

        dotenv_path = PROJECT_ROOT / ".env"
        if _prompt_yes_no("是否将 ARK_API_KEY 写入项目根目录 .env 以便后续复用？", default_yes=True):
            _update_dotenv(dotenv_path, "ARK_API_KEY", api_key)
            print(f"已写入: {dotenv_path}")
            print("提示：后续可用 'set -a; source .env; set +a' (macOS/Linux) 或 'setx ARK_API_KEY \"...\"' (Windows) 设置到环境变量。")
            print("")

    print(f"默认 Model ID: {DEFAULT_MODEL_ID}")
    model_id_input = input("请输入 Model ID（回车使用默认）: ").strip()
    if model_id_input:
        model_id = model_id_input

    out_dir_input = input(f"输出目录（回车使用默认 {DEFAULT_OUT_DIR}）: ").strip()
    if out_dir_input:
        out_dir = Path(out_dir_input).expanduser()

    try:
        kinds = _choose_kinds_interactively()
    except Exception as e:
        print(f"选择失败: {e}", file=sys.stderr)
        return 2

    written = generate(out_dir=out_dir, kinds=kinds, model_id=model_id, base_url=base_url)
    print("")
    print("生成完成：")
    for p in written:
        print(f"- {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))

